// Generated by `bun init`

declare module "*.svg" {
	/**
	 * A path to the SVG file
	 */
	const path: `${string}.svg`;
	export = path;
}

declare module "*.module.css" {
	/**
	 * A record of class names to their corresponding CSS module classes
	 */
	const classes: { readonly [key: string]: string };
	export = classes;
}

// Environment variables
declare module "bun" {
	interface Env {
		ACCESS_TOKEN_SECRET: string;
		REFRESH_TOKEN_SECRET: string;
		DATABASE_PATH: string;
		ACCESS_TOKEN_EXPIRY?: string;
		REFRESH_TOKEN_EXPIRY?: string;
		ALLOWED_ORIGINS?: string;
	}
}
